# Generated by Django 2.0.3 on 2018-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_date',
            field=models.DateField(blank=True),
        ),
    ]
