# Generated by Django 2.0.3 on 2018-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upeweb', '0002_auto_20180401_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
