# Generated by Django 2.1.2 on 2018-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upeweb', '0004_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
