# Generated by Django 2.1.5 on 2019-02-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upeweb', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
