# Generated by Django 2.1.5 on 2019-02-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upeweb', '0008_alumnus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnus',
        ),
    ]
