# Generated by Django 2.2.8 on 2021-02-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_auto_20210202_0225'),
        ('upeweb', '0013_auto_20210202_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='candidate_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
