# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type_id', models.IntegerField()),
                ('need_transportation', models.BooleanField(default=False)),
                ('markdown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('confirmed', models.CharField(choices=[('t', 'Confirmed'), ('f', 'Unconfirmed'), ('r', 'Rejected')], default='f', max_length=1)),
                ('confirm_comment', models.TextField()),
                ('comment', models.TextField()),
                ('transportation', models.IntegerField(choices=[(-1, 'I need a ride'), (0, "Don't worry about me"), (3, 'I have a small sedan (4 seats)'), (4, 'I have a sedan (5 seats)'), (6, 'I have a minivan (7 seats)')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
