from hknweb.candidate.admin.announcement import AnnouncementAdmin
from hknweb.candidate.admin.bitbyteactivity import BitByteActivityAdmin
from hknweb.candidate.admin.officer_challenge import OffChallengeAdmin
