# Generated by Django 2.2.8 on 2021-01-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20210122_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('room_num', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring.Room'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='num_assignments',
            field=models.IntegerField(default=1),
        ),
    ]
