#!/usr/bin/env bash

source ~/.bashrc

DJANGO_DIR=~/hknweb/prod/current
PYTHONPATH=$DJANGO_DIR:$PYTHONPATH

SOCKFILE=/srv/apps/$(whoami)/dev.sock
NUM_WORKERS=4

cd $DJANGO_DIR

exec poetry run gunicorn hknweb.wsgi \
    -w $NUM_WORKERS \
    --log-level debug \
    --log-file - \
    -b unix:"$SOCKFILE"
