# Generated by Django 2.1.11 on 2019-11-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmenttourrequest',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='departmenttourrequest',
            old_name='retype_email_address',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='departmenttourrequest',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
