# Generated by Django 2.2.8 on 2021-11-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_Test',
            new_name='question_text',
        ),
    ]
