# Generated by Django 2.1.11 on 2020-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptour',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='deptour',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='deptour',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='deptour',
            name='verify_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
