# Generated by Django 2.1.11 on 2020-02-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200211_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptour',
            options={'verbose_name': 'Department Tour'},
        ),
        migrations.RemoveField(
            model_name='deptour',
            name='verify_email',
        ),
    ]
