# Generated by Django 2.1.11 on 2020-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200212_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptour',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
