# Generated by Django 2.1.11 on 2020-02-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_deptour_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptour',
            old_name='reviewed',
            new_name='confirmed',
        ),
    ]
