# Generated by Django 2.1.11 on 2020-02-26 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20200218_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptour',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
