# Generated by Django 2.1.11 on 2020-02-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_deptour_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptour',
            name='rsec_comments',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
