# Generated by Django 2.1.11 on 2020-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_deptour_rsec_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptour',
            name='desired_date',
            field=models.DateTimeField(verbose_name='Desired Date and Time'),
        ),
    ]
