# Generated by Django 2.1.11 on 2020-02-26 08:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20200225_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptour',
            name='desired_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deptour',
            name='desired_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
