# Generated by Django 2.1.11 on 2020-02-26 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20200226_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptour',
            name='desired_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
