# Generated by Django 2.1.11 on 2020-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20200226_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptour',
            name='desired_date',
            field=models.DateField(),
        ),
    ]
