# Generated by Django 2.1.11 on 2020-02-26 10:08

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20200226_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptour',
            name='desired_date',
        ),
        migrations.AddField(
            model_name='deptour',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
