# Generated by Django 2.1.11 on 2020-02-27 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20200226_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptour',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Desired Date'),
        ),
        migrations.AlterField(
            model_name='deptour',
            name='desired_time',
            field=models.TimeField(verbose_name='Desired Time'),
        ),
    ]
