# Generated by Django 2.1.11 on 2020-02-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20200226_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptour',
            old_name='rsec_comments',
            new_name='deprel_comments',
        ),
    ]
