# Generated by Django 2.2.8 on 2020-03-18 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20200226_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptour',
            name='confirm_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deptour',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Desired Date'),
        ),
    ]
