# Generated by Django 2.1.5 on 2019-02-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hknweb', '0006_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffChallenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('proof', models.TextField(blank=True, default='', max_length=2000)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hknweb.Profile')),
            ],
        ),
    ]
