# Generated by Django 2.2.8 on 2022-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_squashed_0029_auto_20220210_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
