# Generated by Django 2.2.8 on 2022-04-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_attendanceform_description'),
        ('candidate', '0004_auto_20220404_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementmergerequirement',
            name='event1',
        ),
        migrations.RemoveField(
            model_name='requirementmergerequirement',
            name='event2',
        ),
        migrations.RemoveField(
            model_name='requirementmergerequirement',
            name='linkedRequirement',
        ),
        migrations.RemoveField(
            model_name='requirementmergerequirement',
            name='multiplier1',
        ),
        migrations.RemoveField(
            model_name='requirementmergerequirement',
            name='multiplier2',
        ),
        migrations.AlterField(
            model_name='requirementmergerequirement',
            name='grandTotal',
            field=models.FloatField(default=0.0, help_text='The grand total points needed from the weighted sum of connected events (only needed for the first node)'),
        ),
        migrations.CreateModel(
            name='MergeEventsMultiplierEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False, help_text='Toggle this entry')),
                ('multiplier', models.FloatField(default=1)),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
                ('requirementMergeRequirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.RequirementMergeRequirement')),
            ],
        ),
    ]
