# Generated by Django 2.1.5 on 2019-02-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20190204_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
        ),
    ]
