# Generated by Django 2.2.8 on 2022-05-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesemester', '0002_auto_20210202_0225'),
        ('events', '0008_attendanceform_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0006_auto_20220503_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EventReq',
            fields=[
                ('basereq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidate.BaseReq')),
                ('n', models.PositiveSmallIntegerField()),
                ('event_types', models.ManyToManyField(to='events.EventType')),
            ],
            bases=('candidate.basereq',),
        ),
        migrations.CreateModel(
            name='ExternalReq',
            fields=[
                ('basereq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidate.BaseReq')),
                ('completed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('candidate.basereq',),
        ),
        migrations.CreateModel(
            name='FormReq',
            fields=[
                ('externalreq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidate.ExternalReq')),
                ('link', models.CharField(max_length=150)),
            ],
            bases=('candidate.externalreq',),
        ),
        migrations.CreateModel(
            name='MiscReq',
            fields=[
                ('externalreq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidate.ExternalReq')),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
            ],
            bases=('candidate.externalreq',),
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('min_challenges', models.PositiveSmallIntegerField()),
                ('min_hangouts', models.PositiveSmallIntegerField()),
                ('num_interactivities', models.PositiveSmallIntegerField()),
                ('num_bitbyte', models.PositiveSmallIntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesemester.Semester')),
                ('event_requirements', models.ManyToManyField(to='candidate.EventReq')),
                ('form_reqs', models.ManyToManyField(to='candidate.FormReq')),
                ('misc_reqs', models.ManyToManyField(to='candidate.MiscReq')),
            ],
            options={
                'verbose_name_plural': 'Logistics',
            },
        ),
    ]
