# Generated by Django 2.1.5 on 2019-02-05 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_offchallenge_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='offchallenge',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
