# Generated by Django 2.2.8 on 2022-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_basereq_eventreq_externalreq_formreq_logistics_miscreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='event_requirements',
            field=models.ManyToManyField(blank=True, to='candidate.EventReq'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='form_reqs',
            field=models.ManyToManyField(blank=True, to='candidate.FormReq'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='misc_reqs',
            field=models.ManyToManyField(blank=True, to='candidate.MiscReq'),
        ),
    ]
