# Generated by Django 2.1.5 on 2019-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20190217_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='name',
            field=models.CharField(default='', max_length=85, verbose_name='title'),
        ),
    ]
