# Generated by Django 2.2.8 on 2022-05-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20220503_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='event_requirements',
            new_name='event_reqs',
        ),
    ]
