# Generated by Django 2.2.8 on 2022-05-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20220503_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offchallenge',
            name='csec_confirmed',
        ),
    ]
