# Generated by Django 2.2.8 on 2022-05-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_remove_offchallenge_csec_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offchallenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offchallenge',
            name='officer_comment',
        ),
    ]
