# Generated by Django 2.1.11 on 2019-10-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_auto_20190927_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offchallenge',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='offchallenge',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='offchallenge',
            name='csec_confirmed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offchallenge',
            name='officer_confirmed',
            field=models.NullBooleanField(),
        ),
    ]
