# Generated by Django 2.2.8 on 2022-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_auto_20220504_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='basereq',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbyteactivity',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bitbyteactivity',
            name='proof',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='formreq',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miscreq',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offchallenge',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='offchallenge',
            name='proof',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
