# Generated by Django 2.1.11 on 2019-10-23 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20191019_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='requester',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__permissions__codename': 'add_offchallenge'}, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
