# Generated by Django 2.2.8 on 2022-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20220505_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreq',
            name='due_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
