# Generated by Django 4.2.17 on 2025-11-21 02:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("candidate", "0015_logistics_mandatory_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short code for the URL (e.g., 'discord', 'apply')",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug can only contain letters, numbers, hyphens, and underscores",
                                regex="^[a-zA-Z0-9-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        help_text="Full URL to redirect to", max_length=2000
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for officers",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this shortlink has been used",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this shortlink is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Officer who created this shortlink",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shortlinks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Short Link",
                "verbose_name_plural": "Short Links",
                "ordering": ["-created_at"],
            },
        ),
    ]
