# Generated by Django 4.2.17 on 2026-02-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("candidate", "0015_logistics_mandatory_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitByteGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bits",
                    models.ManyToManyField(
                        related_name="bitbyte_groups_as_bit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bytes",
                    models.ManyToManyField(
                        related_name="bitbyte_groups_as_byte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bit_byte_groups",
                        to="coursesemester.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Byte Group",
                "verbose_name_plural": "Bit Byte Groups",
            },
        ),
    ]
