# Generated by Django 2.2.8 on 2020-02-12 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20191119_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=85)),
                ('duedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(default='', max_length=85)),
            ],
        ),
    ]
