# Generated by Django 2.1.11 on 2020-02-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20191119_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitByteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bit Byte Activities',
            },
        ),
    ]
