# Generated by Django 2.2.8 on 2020-02-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_candidateforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidateforms',
            name='link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidateforms',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='offchallenge',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='title'),
        ),
    ]
