# Generated by Django 2.2.8 on 2020-02-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_auto_20200211_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateform',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
