# Generated by Django 2.2.8 on 2020-03-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_auto_20200228_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitbyteactivity',
            old_name='candidates',
            new_name='participants',
        ),
    ]
