# Generated by Django 2.2.8 on 2021-02-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201012_1603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hknweb', '0013_auto_20210203_2309'),
        ('candidate', '0023_auto_20200331_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('duedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.CharField(blank=True, default='', max_length=150)),
                ('visible', models.BooleanField(default=False)),
                ('candidateSemesterActive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('duedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('instructions', models.CharField(blank=True, default='', max_length=150)),
                ('visible', models.BooleanField(default=False)),
                ('candidateSemesterActive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='candidateform',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester'),
        ),
        migrations.CreateModel(
            name='RequriementEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberRequired', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=False)),
                ('eventsDateStart', models.DateTimeField(blank=True, null=True)),
                ('eventsDateEnd', models.DateTimeField(blank=True, null=True)),
                ('candidateSemesterActive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMergeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enableTitle', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('enable', models.BooleanField(default=False, help_text='Toggle this Merge node (when ON, this will be the first node) (Does not need to be on to be a connected node)')),
                ('multiplier1', models.FloatField(default=1)),
                ('multiplier2', models.FloatField(default=1)),
                ('enableGrandTotal', models.BooleanField(default=False, help_text='Toggle the "Grant Total" field, which will take over the weighted sum total (otherwise, will use weighted sum total) (only needed for the first node)')),
                ('grandTotal', models.FloatField(default=None, help_text='The grand total points needed from the weighted sum of connected events (only needed for the first node)', null=True)),
                ('color', models.CharField(default='#0072c1', max_length=7)),
                ('candidateSemesterActive', models.ForeignKey(help_text='Candidate semester this Merged Requirement will take place (ignored if it is a connected node)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
                ('event1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event1', to='events.EventType')),
                ('event2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event2', to='events.EventType')),
                ('linkedRequirement', models.ForeignKey(blank=True, help_text='Connect to another Merged Requirement node here (Candidate Semester, Grand Total, and all Enable fields for all connected nodes will be ignored) (A Cycle will make the Grand Total equal Infinite (higher precidence to Grand Total and weighted total sum))', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.RequirementMergeRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMandatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('eventsDateStart', models.DateTimeField(blank=True, null=True)),
                ('eventsDateEnd', models.DateTimeField(blank=True, null=True)),
                ('candidateSemesterActive', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
                ('events', models.ManyToManyField(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementHangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('officer_hangout', 'Officer Hangouts'), ('officer_challenge', 'Officer Challenges'), ('either', 'Either')], max_length=255)),
                ('numberRequired', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=False)),
                ('hangoutsDateStart', models.DateTimeField(blank=True, null=True)),
                ('hangoutsDateEnd', models.DateTimeField(blank=True, null=True)),
                ('candidateSemesterActive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementBitByteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('numberRequired', models.IntegerField(default=0)),
                ('candidateSemesterActive', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hknweb.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='DuePaymentPaidEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('duePayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.DuePayment')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Due Payment Paid Entries',
            },
        ),
        migrations.CreateModel(
            name='CommitteeProjectDoneEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('committeeProject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.CommitteeProject')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Committee Project Done Entries',
            },
        ),
        migrations.CreateModel(
            name='CandidateFormDoneEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.CandidateForm')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidate Form Done Entries',
            },
        ),
    ]
