# Generated by Django 2.2.8 on 2021-10-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_auto_20210204_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmergerequirement',
            name='linkedRequirement',
            field=models.ForeignKey(blank=True, help_text='Connect to another Merged Requirement node here (Candidate Semester, Grand Total, and all Enable fields for all subsequent connected nodes will be ignored) (A Cycle will make the Grand Total equal Infinite (higher precidence to Grand Total and weighted total sum))', null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate.RequirementMergeRequirement'),
        ),
        migrations.AlterField(
            model_name='requriementevent',
            name='numberRequired',
            field=models.IntegerField(default=0, help_text='Number of events needed to satisfy this requirement (set to -1 for ALL events of evenType and between the eventsDateStart and eventsDateEnd, if filled)'),
        ),
    ]
