# Generated by Django 2.2.8 on 2022-02-11 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_auto_20211014_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeprojectdoneentry',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
