# Generated by Django 2.2.8 on 2020-07-14 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icsr',
            name='icsr_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icsr_course', to='academics.Course'),
        ),
        migrations.AlterField(
            model_name='icsr',
            name='icsr_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icsr_department', to='academics.Department'),
        ),
        migrations.AlterField(
            model_name='icsr',
            name='icsr_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icsr_instructor', to='academics.Instructor'),
        ),
        migrations.AlterField(
            model_name='icsr',
            name='icsr_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icsr_semester', to='academics.Semester'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='academicentity_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='academics.AcademicEntity'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.TextField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_question', to='academics.Question'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_survey', to='academics.Survey'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1915)]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='num_students',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='response_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_icsr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_icsr', to='academics.ICSR'),
        ),
    ]
