# Generated by Django 2.2.8 on 2021-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icsr',
            name='section_type',
        ),
        migrations.AddField(
            model_name='icsr',
            name='course_name',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
