# Generated by Django 2.2.8 on 2020-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20200714_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
