# Generated by Django 4.2.17 on 2025-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_auto_20211223_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icsr",
            name="course_name",
            field=models.TextField(default="", max_length=500),
        ),
    ]
