# Generated by Django 2.1.2 on 2018-10-16 06:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'hour', models.IntegerField(choices=[
                        (11, '11am'), (12, '12pm'),
                        (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'),
                    ]),
                ),
                ('day', models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')])),
                ('room', models.IntegerField(choices=[(0, 'Cory'), (1, 'Soda')])),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(to='tutoring.Course')),
                ('slots', models.ManyToManyField(to='tutoring.Slot')),
            ],
        ),
    ]
