# Generated by Django 2.1.2 on 2018-10-12 07:24
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [('tutoring', '0001_initial'), ('tutoring', '0002_auto_20181012_0644')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(to='tutoring.Course')),
                ('slots', models.ManyToManyField(to='tutoring.Slot')),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='starttime',
        ),
        migrations.AddField(
            model_name='slot',
            name='hour',
            field=models.IntegerField(
                choices=[
                    (11, '11am'), (12, '12pm'), (13, '1pm'),
                    (14, '2pm'), (15, '3pm'), (16, '4pm'),
                ], default=11,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='room',
            field=models.IntegerField(choices=[(0, 'Cory'), (1, 'Soda')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='day',
            field=models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
