# Generated by Django 2.2.8 on 2020-01-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='tutors',
            field=models.ManyToManyField(to='tutoring.Tutor'),
        ),
    ]
