# Generated by Django 2.2.8 on 2021-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(1, 'Mon'), (3, 'Wed'), (5, 'Fri')]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.IntegerField(choices=[(13, '1pm'), (14, '2pm'), (15, '3pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm')]),
        ),
        migrations.AlterField(
            model_name='timeslotpreference',
            name='office_preference',
            field=models.IntegerField(default=0),
        ),
    ]
