# Generated by Django 2.2.8 on 2022-05-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_squashed_0007_auto_20220127_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompreference',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='room',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='CoursePreference',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomPreference',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='TimeSlotPreference',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorCourse',
        ),
    ]
