# Generated by Django 2.1.2 on 2018-10-12 06:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='starttime',
        ),
        migrations.AddField(
            model_name='slot',
            name='hour',
            field=models.IntegerField(
                choices=[
                    (11, '11am'), (12, '12pm'), (13, '1pm'),
                    (14, '2pm'), (15, '3pm'), (16, '4pm'),
                ], default=11,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='room',
            field=models.IntegerField(choices=[(0, 'Cory'), (1, 'Soda')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='day',
            field=models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
