# Generated by Django 2.2.8 on 2022-05-22 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursesemester', '0002_auto_20210202_0225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0002_auto_20220522_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringLogistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour_tutors', models.ManyToManyField(blank=True, related_name='one_hour_tutoring', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesemester.Semester')),
                ('two_hour_tutors', models.ManyToManyField(blank=True, related_name='two_hour_tutoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('num_tutors', models.IntegerField()),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.TutoringLogistics')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Room')),
                ('tutor_prefs', models.ManyToManyField(blank=True, related_name='tutoring_slotprefs', to=settings.AUTH_USER_MODEL)),
                ('tutors', models.ManyToManyField(blank=True, related_name='tutoring_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
