# Generated by Django 2.2.28 on 2022-11-29 01:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesemester', '0002_auto_20210202_0225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutoring', '0002_auto_20221006_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringLogistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour_tutors', models.ManyToManyField(blank=True, related_name='one_hour_tutoring', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursesemester.Semester')),
                ('two_hour_tutors', models.ManyToManyField(blank=True, related_name='two_hour_tutoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TutoringLogistics',
            },
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='roompreference',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_id',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='DarkGray', max_length=25),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='slot',
            name='num_tutors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='slot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring.Room'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='tutoring_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CoursePreference',
        ),
        migrations.DeleteModel(
            name='RoomPreference',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='TimeSlotPreference',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorCourse',
        ),
        migrations.AddField(
            model_name='slot',
            name='logistics',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring.TutoringLogistics'),
        ),
    ]
