# Generated by Django 2.2.8 on 2021-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20210128_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.IntegerField(choices=[(13, '1pm'), (14, '2pm'), (19, '7pm'), (20, '8pm'), (21, '9pm')]),
        ),
    ]
