# Generated by Django 2.2.8 on 2022-05-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_room_slot_tutoringlogistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoringlogistics',
            options={'verbose_name_plural': 'TutoringLogistics'},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='tutor_prefs',
        ),
        migrations.AddField(
            model_name='room',
            name='color',
            field=models.CharField(default='DarkGray', max_length=25),
        ),
    ]
