# Mostly Generated by Django 4.2.17, create_tutors manually created

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_tutors(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Tutor = apps.get_model('tutoring', 'Tutor')
    tutoring_users = User.objects.exclude(
        one_hour_tutoring__isnull=True,
        two_hour_tutoring__isnull=True,
        tutoring_slots__isnull=True
    ).distinct().iterator()
    Tutor.objects.bulk_create(
        ( Tutor(user=user) for user in tutoring_users ),
        ignore_conflicts=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("tutoring", "0003_auto_20221128_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tutoring_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_tutors",
                        to="coursesemester.course",
                    ),
                ),
                (
                    "in_progress_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="in_progress_tutors",
                        to="coursesemester.course",
                    ),
                ),
                (
                    "preferred_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_tutors",
                        to="coursesemester.course",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_tutors, elidable=True),
        migrations.AlterField(
            model_name="slot",
            name="tutors",
            field=models.ManyToManyField(
                blank=True, related_name="tutoring_slots", to="tutoring.tutor"
            ),
        ),
        migrations.AlterField(
            model_name="tutoringlogistics",
            name="one_hour_tutors",
            field=models.ManyToManyField(
                blank=True, related_name="one_hour_tutoring", to="tutoring.tutor"
            ),
        ),
        migrations.AlterField(
            model_name="tutoringlogistics",
            name="two_hour_tutors",
            field=models.ManyToManyField(
                blank=True, related_name="two_hour_tutoring", to="tutoring.tutor"
            ),
        ),
    ]
