# Generated by Django 4.2.17 on 2025-12-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0013_alter_coursedescription_description_and_more"),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("tutoring", "0003_auto_20221128_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="CribSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.URLField(blank=True, max_length=300)),
                ("comment", models.CharField(blank=True, max_length=300)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studentservices.coursedescription",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursesemester.semester",
                    ),
                ),
            ],
        ),
    ]
