# Generated by Django 4.2.17 on 2026-01-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0014_coursedescription_folderid"),
        ("coursesemester", "0002_auto_20210202_0225"),
        ("tutoring", "0003_auto_20221128_1703"),
    ]

    operations = [
        migrations.CreateModel(
            name="CribSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studentservices.coursedescription",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursesemester.semester",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cribsheet",
            constraint=models.UniqueConstraint(
                fields=("semester", "course", "title"),
                name="unique_cribsheet_per_course_per_semester",
            ),
        ),
    ]
