# Generated by Django 2.2.8 on 2020-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20200524_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotpreference',
            name='availability',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slotpreference',
            name='office_pref',
            field=models.IntegerField(default=2),
        ),
    ]
