# Generated by Django 2.2.8 on 2022-06-02 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20220526_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='datetime',
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 2, 18, 33, 41, 825151, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='weekday',
            field=models.IntegerField(choices=[('Sun', 0), ('Mon', 1), ('Tue', 2), ('Wed', 3), ('Thu', 4), ('Fri', 5), ('Sat', 6)], default=1),
            preserve_default=False,
        ),
    ]
