# Generated by Django 2.2.8 on 2021-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20210202_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.IntegerField(choices=[(13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (21, '9pm')]),
        ),
    ]
