# Generated by Django 2.2.8 on 2022-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_auto_20220602_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')]),
        ),
    ]
