# Generated by Django 2.2.8 on 2021-09-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_auto_20210902_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='office_preference',
        ),
        migrations.RemoveField(
            model_name='timeslotpreference',
            name='time_preference',
        ),
        migrations.AddField(
            model_name='timeslotpreference',
            name='preference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='num_assignments',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='RoomPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Room')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.TimeSlot')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Tutor')),
            ],
        ),
    ]
