# Generated by Django 2.2.8 on 2022-01-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20210907_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.IntegerField(choices=[(12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (20, '8pm'), (21, '9pm')]),
        ),
    ]
