# Generated by Django 2.2.8 on 2020-09-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20200609_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(choices=[(11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm')])),
                ('day', models.IntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri')])),
                ('timeslot_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlotPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_preference', models.IntegerField(default=1)),
                ('office_preference', models.IntegerField(default=2)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.TimeSlot')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.Tutor')),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='hour',
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SlotPreference',
        ),
        migrations.AddField(
            model_name='slot',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring.TimeSlot'),
        ),
    ]
