# Generated by Django 2.2.8 on 2020-09-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_auto_20200906_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepreference',
            name='rating',
        ),
        migrations.AddField(
            model_name='coursepreference',
            name='preference',
            field=models.IntegerField(default=-1),
        ),
    ]
