# Generated by Django 2.2.8 on 2020-09-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_auto_20200906_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cory_preference',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='soda_preference',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='num_assignments',
            field=models.IntegerField(default=2),
        ),
    ]
