# Generated by Django 4.2.17 on 2025-02-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hknweb", "0024_profile_preferred_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResume",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current", models.BooleanField()),
                ("pdf", models.FileField(upload_to="resume/")),
                (
                    "userInfo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="hknweb.profile"
                    ),
                ),
            ],
        ),
    ]
