# Generated by Django 4.2.19 on 2025-04-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hknweb", "0025_remove_profile_resume"),
        ("indrel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="indrel/resumebooks/")),
                ("iso", models.FileField(upload_to="indrel/resumebooks/")),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userresume",
            name="current",
        ),
        migrations.RemoveField(
            model_name="userresume",
            name="pdf",
        ),
        migrations.AddField(
            model_name="userresume",
            name="resume",
            field=models.FileField(null=True, upload_to="indrel/resume/"),
        ),
        migrations.AddField(
            model_name="userresume",
            name="upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userresume",
            name="userInfo",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to="hknweb.profile",
            ),
        ),
    ]
