# Generated by Django 2.0.3 on 2018-04-23 06:54

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownpage',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
