# Generated by Django 2.1.2 on 2018-10-16 18:55
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('is_exec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.Committee')),
            ],
        ),
    ]
