# Generated by Django 2.0.3 on 2018-04-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('personal_email', models.CharField(max_length=225)),
            ],
        ),
    ]
