# Generated by Django 2.0.3 on 2018-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='personal_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='officer',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
