# Generated by Django 2.1.2 on 2018-10-16 18:38
from django.db import migrations

committees = [
    ('pres', 'President'),
    ('vp', 'Vice President'),
    ('rsec', 'Recording Secretary'),
    ('csec', 'Corresponding Secretary'),
    ('treas', 'Treasurer'),
    ('deprel', 'Department Relations'),
    ('alumrel', 'Alumni Relations'),
    ('act', 'Activities'),
    ('bridge', 'Bridge'),
    ('compserv', 'Computing Services'),
    ('decal', 'Decal'),
    ('indrel', 'Industrial Relations'),
    ('serv', 'Service'),
    ('studrel', 'Student Relations'),
    ('tutoring', 'Tutoring'),
    ('pub', 'Publicity'),
    ('examfiles', 'Exam Files'),
]

execs = [
    'pres',
    'vp',
    'rsec',
    'treas',
    'csec',
    'deprel',
    'alumrel',
]


def create_committees(apps, schema_editor):
    Committee = apps.get_model('officers', 'Committee')
    for short, name in committees:
        Committee.objects.create(short=short, name=name, is_exec=(short in execs))


def destroy_committees(apps, schema_editor):
    Committee = apps.get_model('officers', 'Committee')
    Committee.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_committees, destroy_committees),
    ]
