# Generated by Django 2.0.3 on 2018-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_auto_20180423_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
    ]
