# Generated by Django 2.0.3 on 2018-04-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_officer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='imange',
            field=models.CharField(default='', max_length=255),
        ),
    ]
