# Generated by Django 2.1.5 on 2019-02-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20190205_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='offchallenge',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
