# Generated by Django 2.1.9 on 2019-09-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20190223_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=85)),
                ('text', models.TextField(blank=True, default='', max_length=2000)),
                ('visible', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
