# Generated by Django 2.1.11 on 2019-10-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_auto_20191019_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='csec_confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='offchallenge',
            name='officer_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
