# Generated by Django 2.1.11 on 2019-11-20 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20191022_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
