# Generated by Django 2.2.8 on 2020-02-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20200211_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateForms',
            new_name='CandidateForm',
        ),
    ]
