# Generated by Django 2.2.8 on 2020-02-19 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0019_candidateform_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offchallenge',
            name='officer',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offchallenge',
            name='requester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BitByteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('confirm_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(default=None, limit_choices_to={'groups__name': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bit Byte Activities',
            },
        ),
    ]
