# Generated by Django 2.2.8 on 2020-03-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20200306_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitbyteactivity',
            name='proof',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
