# Generated by Django 2.2.8 on 2021-02-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_auto_20210202_0210'),
        ('coursesemester', '0002_auto_20210202_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='committeeproject',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='duepayment',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='requirementbitbyteactivity',
            name='candidateSemesterActive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='requirementhangout',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='requirementmandatory',
            name='candidateSemesterActive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='requirementmergerequirement',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.AlterField(
            model_name='requriementevent',
            name='candidateSemesterActive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
    ]
