# Generated by Django 2.2.8 on 2022-02-28 20:52

import django.core.validators
from django.db import migrations, models
import hknweb.alumni.models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_squashed_0016_auto_20190219_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1915), hknweb.alumni.models.max_value_current_year], verbose_name='graduation year'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
