# Generated by Django 2.1.3 on 2018-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20181105_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnus',
            name='name_id',
        ),
        migrations.AddField(
            model_name='alumnus',
            name='suggestions',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
