# Generated by Django 2.2.8 on 2022-03-04 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20220228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='salary',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
