# Generated by Django 2.1.11 on 2020-03-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20200209_1827'),
        ('alumni', '0005_auto_20200211_2107'),
    ]

    operations = [
    ]
