# Generated by Django 2.2.8 on 2022-02-28 05:15

import django.core.validators
from django.db import migrations, models
import hknweb.alumni.models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20210204_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1915), hknweb.alumni.models.max_value_current_year], verbose_name='graduation year'),
        ),
    ]
