# Generated by Django 2.1.3 on 2018-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20181106_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_season',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=6, verbose_name='graduation season'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='suggestions',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
