# Generated by Django 2.1.3 on 2018-11-09 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20181108_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnus',
            options={'verbose_name_plural': 'alumni'},
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
