# Generated by Django 2.1.5 on 2019-02-04 19:09

import django.core.validators
from django.db import migrations, models
import hknweb.alumni.models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_alumnus_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_year',
            field=models.IntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1915), hknweb.alumni.models.max_value_current_year], verbose_name='graduation year'),
        ),
    ]
