# Generated by Django 2.1.2 on 2018-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0003_auto_20180406_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('redirect', models.URLField()),
            ],
        ),
    ]
