# Generated by Django 2.1.2 on 2018-11-16 20:58
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0004_auto_20181019_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('is_exec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hknweb.Committee')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hknweb.Profile')),
            ],
        ),
    ]
