# Generated by Django 2.2.8 on 2020-02-19 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0009_delete_alumnus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=85)),
                ('text', models.TextField(blank=True, default='', max_length=2000)),
                ('visible', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
