# Generated by Django 2.2.8 on 2020-04-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0011_reviewsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewSession',
        ),
    ]
