# Generated by Django 2.1.11 on 2020-03-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0010_announcement'),
        ('hknweb', '0011_auto_20200209_1848'),
    ]

    operations = [
    ]
