# Generated by Django 2.2.8 on 2022-02-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('hknweb', '0014_auto_20210202_0225'), ('hknweb', '0015_auto_20211010_0141'), ('hknweb', '0016_profile_google_calendar_id'), ('hknweb', '0017_auto_20220228_0019')]

    dependencies = [
        ('candidate', '0025_auto_20210202_0225'),
        ('hknweb', '0013_auto_20210202_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='candidate_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Formats: '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y' (Examples: '2006-10-25', '10/25/2006', '10/25/06')", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_date',
            field=models.DateField(blank=True, help_text="Formats: '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y' (Examples: '2006-10-25', '10/25/2006', '10/25/06')", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='candidate_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesemester.Semester'),
        ),
    ]
