# Generated by Django 2.2.8 on 2022-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0014_auto_20210202_0225_squashed_0017_auto_20220228_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProvisioningPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
