# Generated by Django 2.2.8 on 2022-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0015_auto_20211010_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
