# Generated by Django 2.2.8 on 2022-05-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesemester', '0002_auto_20210202_0225'),
        ('hknweb', '0016_committee_committeeship_elections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elections',
            new_name='Election',
        ),
    ]
