# Generated by Django 2.2.8 on 2022-05-19 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hknweb', '0018_auto_20220518_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeship',
            name='users',
        ),
        migrations.AddField(
            model_name='committeeship',
            name='assistant_officers',
            field=models.ManyToManyField(related_name='ao_ships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committeeship',
            name='committee_members',
            field=models.ManyToManyField(related_name='cmemberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committeeship',
            name='officers',
            field=models.ManyToManyField(related_name='officerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
