# Generated by Django 2.2.8 on 2022-05-19 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0019_auto_20220518_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeship',
            name='assistant_officers',
            field=models.ManyToManyField(blank=True, related_name='ao_ships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committeeship',
            name='committee_members',
            field=models.ManyToManyField(blank=True, related_name='cmemberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committeeship',
            name='officers',
            field=models.ManyToManyField(blank=True, related_name='officerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
