# Generated by Django 2.2.8 on 2022-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0021_auto_20220520_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_exec',
            field=models.BooleanField(default=False),
        ),
    ]
