# Generated by Django 2.2.8 on 2022-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0022_committee_is_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
