# Generated by Django 2.2.8 on 2022-06-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesemester', '0002_auto_20210202_0225'),
        ('hknweb', '0023_auto_20220521_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_courses',
            field=models.ManyToManyField(blank=True, to='coursesemester.Course'),
        ),
    ]
