# Generated by Django 4.2.17 on 2026-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hknweb", "0024_profile_preferred_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveFolderID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("folderID", models.CharField(max_length=50)),
            ],
        ),
    ]
