# Generated by Django 2.2.28 on 2022-12-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0024_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
