# Generated by Django 4.2.19 on 2025-04-08 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hknweb", "0024_profile_preferred_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="resume",
        ),
    ]
