# Generated by Django 2.0.3 on 2018-04-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('Electrical Engineering', 'ee')], max_length=2),
        ),
    ]
