# Generated by Django 2.0.3 on 2018-04-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20180423_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesemester',
            old_name='course',
            new_name='course_id',
        ),
    ]
