# Generated by Django 2.0.3 on 2018-04-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20180423_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesemester',
            name='course_id',
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Course'),
        ),
    ]
