# Generated by Django 2.1.11 on 2019-10-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('exams', '0009_auto_20190421_2337'), ('exams', '0010_auto_20190421_2343'), ('exams', '0011_auto_20190422_0112'), ('exams', '0012_auto_20191001_2145')]

    dependencies = [
        ('exams', '0008_auto_20190421_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesemester',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Instructor'),
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='release',
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='release',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
