# Generated by Django 2.1.7 on 2019-04-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20190421_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemester',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Instructor'),
        ),
    ]
