# Generated by Django 2.1.11 on 2019-10-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20190422_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
