# Generated by Django 2.2.8 on 2020-04-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20200405_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemester',
            name='semester',
            field=models.CharField(max_length=255),
        ),
    ]
