# Generated by Django 2.2.8 on 2020-04-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20200405_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
