# Generated by Django 2.2.8 on 2020-04-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='exams.Semester'),
            preserve_default=False,
        ),
    ]
