# Generated by Django 2.2.8 on 2020-04-12 23:08

from django.db import migrations, models
import hknweb.exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_exam_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructor',
            field=models.CharField(default='ProfBob', max_length=255, verbose_name=hknweb.exams.models.Instructor),
        ),
        migrations.AddField(
            model_name='exam',
            name='solution',
            field=models.BooleanField(default=False),
        ),
    ]
