# Generated by Django 2.2.8 on 2020-04-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200412_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='abbreviated_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='subject',
            new_name='long_name',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
