# Generated by Django 2.2.8 on 2020-04-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_auto_20200412_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_Choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.ExamChoice'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Instructor'),
        ),
        migrations.DeleteModel(
            name='CourseSemester',
        ),
    ]
