# Generated by Django 2.2.8 on 2020-04-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20200413_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.BooleanField()),
                ('midterm1', models.FileField(blank=True, upload_to='')),
                ('midterm1_sol', models.FileField(blank=True, upload_to='')),
                ('midterm2', models.FileField(blank=True, upload_to='')),
                ('midterm2_sol', models.FileField(blank=True, upload_to='')),
                ('midterm3', models.FileField(blank=True, upload_to='')),
                ('midterm3_sol', models.FileField(blank=True, upload_to='')),
                ('final', models.FileField(blank=True, upload_to='')),
                ('final_sol', models.FileField(blank=True, upload_to='')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Instructor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Semester')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamChoice',
        ),
    ]
