# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_permission_group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='view_permission_group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='person_id',
            field=models.IntegerField(null=True),
        ),
    ]
