# Generated by Django 2.2.8 on 2022-03-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220228_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCalAccessLevelMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(0, 'internal'), (1, 'candidate'), (2, 'external')], default=0)),
                ('calendar_id', models.CharField(max_length=255)),
            ],
        ),
    ]
