# Generated by Django 2.2.8 on 2022-03-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220303_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set(),
        ),
    ]
