# Generated by Django 2.1.5 on 2019-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190220_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='confirm_comment',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_limit',
            field=models.PositiveIntegerField(default=999999, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
