# Generated by Django 2.1.5 on 2019-02-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190220_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvps',
            field=models.IntegerField(default=0),
        ),
    ]
