# Generated by Django 2.2.8 on 2022-03-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_attendanceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.AttendanceForm')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Rsvp')),
            ],
        ),
    ]
