# Generated by Django 2.1.5 on 2019-02-22 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0005_delete_link'),
        ('events', '0006_event_rsvps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hknweb.Profile'),
            preserve_default=False,
        ),
    ]
