# Generated by Django 2.2.8 on 2022-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_attendanceresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceresponse',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
