# Generated by Django 2.1.5 on 2019-02-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190224_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rsvp_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
