# Generated by Django 2.2.8 on 2022-05-07 01:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_attendanceform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=500),
        ),
    ]
