# Generated by Django 2.1.9 on 2019-09-20 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190227_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 20, 23, 11, 43, 6094, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
