# Generated by Django 2.2.8 on 2022-05-20 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20220506_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
