# Generated by Django 4.2.5 on 2023-11-29 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_icalview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icalview",
            options={"verbose_name": "iCal view"},
        ),
    ]
