# Generated by Django 4.2.5 on 2024-12-07 02:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_icalview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icalview",
            options={"verbose_name": "iCal view"},
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=markdownx.models.MarkdownxField(max_length=2000),
        ),
    ]
