# Generated by Django 4.2.11 on 2024-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_icalview_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="point_of_contact",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
