# Generated by Django 4.2.17 on 2025-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_alter_icalview_options_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="point_of_contact",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
