# Generated by Django 2.2.8 on 2020-10-12 23:03

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'internal'), (1, 'candidate'), (2, 'external')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
