# Generated by Django 2.2.8 on 2022-02-28 22:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0002_reviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('datetime', models.DateTimeField(default=datetime.date.today, verbose_name='Desired Date and Time')),
                ('phone', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Enter a valid 10-digit phone number in the format: '9876543210'", regex='^\\+?1?\\d{10}$')])),
                ('comments', models.TextField(blank=True, default='', max_length=10000, verbose_name='Additional comments')),
                ('date_submitted', models.DateTimeField(default=datetime.datetime.now)),
                ('confirmed', models.BooleanField(default=False)),
                ('deprel_comments', models.TextField(blank=True, default='', max_length=10000)),
            ],
            options={
                'verbose_name': 'Department Tour',
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
