# Generated by Django 2.2.8 on 2022-03-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0003_auto_20220228_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGuideNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGuideGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.ManyToManyField(to='studentservices.CourseGuideNode')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGuideAdjacencyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_list_source', to='studentservices.CourseGuideNode')),
                ('targets', models.ManyToManyField(related_name='adjacency_list_target', to='studentservices.CourseGuideNode')),
            ],
        ),
    ]
