# Generated by Django 2.2.8 on 2022-03-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0004_courseguideadjacencylist_courseguidegroup_courseguidenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseguidenode',
            name='is_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseguidenode',
            name='x_0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseguidenode',
            name='y_0',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
