# Generated by Django 2.2.8 on 2022-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0005_auto_20220303_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGuideParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_distance', models.IntegerField()),
                ('circle_radius', models.IntegerField()),
                ('force_strength', models.IntegerField()),
                ('marker_width', models.IntegerField()),
                ('marker_height', models.IntegerField()),
            ],
        ),
    ]
