# Generated by Django 2.2.8 on 2022-03-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0006_courseguideparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseguidegroup',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
