# Generated by Django 2.2.8 on 2022-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0007_courseguidegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='notes',
            field=models.TextField(max_length=10000),
        ),
    ]
