# Generated by Django 2.2.8 on 2022-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentservices', '0008_auto_20220402_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewSession',
        ),
    ]
