# Generated by Django 4.2.5 on 2024-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0010_auto_20220421_0027"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "quick_links_raw",
                    models.TextField(
                        blank=True,
                        help_text="Enter each link on a new line in the format: Name | URL",
                        verbose_name="Quick Links",
                    ),
                ),
                (
                    "prerequisites_raw",
                    models.TextField(
                        blank=True,
                        help_text="Enter each prerequisite on a new line.",
                        verbose_name="Prerequisites",
                    ),
                ),
                (
                    "topics_covered_raw",
                    models.TextField(
                        blank=True,
                        help_text="Enter each topic on a new line. Use '-' for subtopics (e.g., Main Topic\n- Subtopic).",
                        verbose_name="Topics Covered",
                    ),
                ),
                (
                    "more_info",
                    models.TextField(
                        blank=True,
                        help_text="Text where lines surrounded by * will be bold (e.g., *bold text*).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
