# Generated by Django 4.2.17 on 2025-04-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0011_coursedescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseguidenode",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
