# Generated by Django 4.2.19 on 2025-04-21 15:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0011_coursedescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursedescription",
            name="prerequisites_raw",
        ),
        migrations.RemoveField(
            model_name="coursedescription",
            name="quick_links_raw",
        ),
        migrations.RemoveField(
            model_name="coursedescription",
            name="topics_covered_raw",
        ),
        migrations.AddField(
            model_name="coursedescription",
            name="prerequisites",
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="coursedescription",
            name="quick_links",
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="coursedescription",
            name="topics_covered",
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="coursedescription",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="coursedescription",
            name="more_info",
            field=markdownx.models.MarkdownxField(blank=True, max_length=2000),
        ),
    ]
