# Generated by Django 4.2.17 on 2025-05-31 02:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0012_remove_coursedescription_prerequisites_raw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedescription",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="coursedescription",
            name="more_info",
            field=markdownx.models.MarkdownxField(blank=True, max_length=10000),
        ),
    ]
