# Generated by Django 4.2.17 on 2026-01-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0013_alter_coursedescription_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedescription",
            name="folderID",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
