# Generated by Django 4.2.17 on 2025-09-19 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studentservices", "0012_courseguidenode_level"),
        ("studentservices", "0013_alter_coursedescription_description_and_more"),
    ]

    operations = []
