# Generated by Django 2.0.3 on 2018-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prerequisites', models.TextField()),
                ('workload', models.TextField()),
                ('topic_covered', models.TextField()),
            ],
        ),
    ]
