# Generated by Django 2.2.8 on 2022-02-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
