# Generated by Django 2.2.8 on 2020-04-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Resume',
        ),
    ]
