# Generated by Django 2.2.8 on 2020-04-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200405_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='document',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
