# Generated by Django 2.2.8 on 2020-04-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200419_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
