# Generated by Django 2.2.8 on 2020-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='critiques',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
