# Generated by Django 2.2.8 on 2020-04-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_critiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
