# Generated by Django 2.1.9 on 2019-09-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_squashed_0016_auto_20190219_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
