# Generated by Django 2.1.3 on 2018-11-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20181105_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
