# Generated by Django 2.2.8 on 2021-02-04 09:18

import django.core.validators
from django.db import migrations, models
import upeweb.alumni.models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20200211_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1915), upeweb.alumni.models.max_value_current_year], verbose_name='graduation year'),
        ),
    ]
