# Generated by Django 2.1.3 on 2018-11-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20181109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_season',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], default='Fall', max_length=6, verbose_name='graduation season'),
        ),
    ]
