# Generated by Django 2.1.7 on 2019-02-19 08:32
import django.core.validators
from django.db import migrations
from django.db import models

import upeweb.alumni.models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_alumnus_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='grad_year',
            field=models.IntegerField(
                default=2019, validators=[
                    django.core.validators.MinValueValidator(
                    1915,
                    ), upeweb.alumni.models.max_value_current_year,
                ], verbose_name='graduation year',
            ),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='mailing_list',
            field=models.BooleanField(default=True),
        ),
    ]
