# Generated by Django 2.2 on 2019-04-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
