# Generated by Django 2.1.7 on 2019-04-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0002_auto_20190406_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.RenameField(
            model_name='links',
            old_name='leader',
            new_name='creator',
        ),
    ]
