# Generated by Django 2.2.8 on 2020-11-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0002_auto_20200213_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='leader',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
