# Generated by Django 2.2.8 on 2021-02-27 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortlinks', '0003_auto_20201121_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='creator',
        ),
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
