# Generated by Django 2.1.5 on 2019-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171128_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='markdown',
        ),
        migrations.RemoveField(
            model_name='event',
            name='need_transportation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rsvp_permission_group_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='view_permission_group_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
