# Generated by Django 2.1.5 on 2019-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190213_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='transportation',
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
