# Generated by Django 2.0.3 on 2018-04-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20180423_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesemester',
            name='final_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='midterm1_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='midterm2_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='midterm3_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering')], max_length=2),
        ),
    ]
