# Generated by Django 2.1.7 on 2019-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190421_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
