# Generated by Django 2.1.7 on 2019-04-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190421_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemester',
            name='semester',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
