name: Setup hknweb test environment

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda info -a
      - name: Create environment
        run: |
          conda env create -f config/hknweb-dev.yml
          conda activate hknweb-dev
      - name: Provision database
        run: python manage.py migrate
