name: Formatting check for Python files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: bash ./scripts/setup_env.sh
      - name: Run formatting check
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate hknweb-dev
          black . --check
