name: Endpoint Permission Sanity Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    steps:
      - uses: ./.github/workflows/setup_test_environment.yaml
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Handler privacy check
        run: |
          pytest tests/test_handler_privacy.py
