name: Run Django unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: bash ./scripts/setup_env.sh
      - name: Run Django unit tests
        run: |
          conda activate hknweb-dev
          coverage run
          coverage report
