name: Run Django unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    steps:
      - uses: ./.github/workflows/setup_test_environment.yaml
      - name: Run Django unit tests
        run: |
          coverage run
          coverage report
